import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { useEffect, useState } from "react";
import { Client } from "@bidiffy/general-backend-sdk";

const client = new Client();
client.configure();


const Home: NextPage = () => {

  const [helloVal,setHelloVal] = useState('...  Waiting ')

  const GetHelloApi = async () =>{
    client.sayHello().then((res:string)=>{
      setHelloVal(res)

    }).catch((err:any)=>console.error(err))
  }
  useEffect(() => {
    GetHelloApi()


  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>BIDIF FRONTEND PLATFORM </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         API SAY : {helloVal}
        </h1>

      </main>

    </div>
  )
}

export default Home
